-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SRdb.Object.Player exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SRdb.InputObject
import SRdb.Interface
import SRdb.Object
import SRdb.Scalar
import SRdb.ScalarCodecs
import SRdb.Union


rankingid : SelectionSet String SRdb.Object.Player
rankingid =
    Object.selectionForField "String" "rankingid" [] Decode.string


{-| The document's ID.
-}
id_ : SelectionSet SRdb.ScalarCodecs.Id SRdb.Object.Player
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (SRdb.ScalarCodecs.codecs |> SRdb.Scalar.unwrapCodecs |> .codecId |> .decoder)


rank : SelectionSet Int SRdb.Object.Player
rank =
    Object.selectionForField "Int" "rank" [] Decode.int


uid : SelectionSet String SRdb.Object.Player
uid =
    Object.selectionForField "String" "uid" [] Decode.string


challengerid : SelectionSet (Maybe String) SRdb.Object.Player
challengerid =
    Object.selectionForField "(Maybe String)" "challengerid" [] (Decode.string |> Decode.nullable)


{-| The document's timestamp.
-}
ts_ : SelectionSet SRdb.ScalarCodecs.Long SRdb.Object.Player
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (SRdb.ScalarCodecs.codecs |> SRdb.Scalar.unwrapCodecs |> .codecLong |> .decoder)
