-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SRdb.Object.RankingPage exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SRdb.InputObject
import SRdb.Interface
import SRdb.Object
import SRdb.Scalar
import SRdb.ScalarCodecs
import SRdb.Union


{-| The elements of type 'Ranking' in this page.
-}
data :
    SelectionSet decodesTo SRdb.Object.Ranking
    -> SelectionSet (List (Maybe decodesTo)) SRdb.Object.RankingPage
data object_ =
    Object.selectionForCompositeField "data" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| A cursor for elements coming after the current page.
-}
after : SelectionSet (Maybe String) SRdb.Object.RankingPage
after =
    Object.selectionForField "(Maybe String)" "after" [] (Decode.string |> Decode.nullable)


{-| A cursor for elements coming before the current page.
-}
before : SelectionSet (Maybe String) SRdb.Object.RankingPage
before =
    Object.selectionForField "(Maybe String)" "before" [] (Decode.string |> Decode.nullable)
