-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SRdb.Object.Ranking exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SRdb.InputObject
import SRdb.Interface
import SRdb.Object
import SRdb.Scalar
import SRdb.ScalarCodecs
import SRdb.Union


rankingowneraddr : SelectionSet String SRdb.Object.Ranking
rankingowneraddr =
    Object.selectionForField "String" "rankingowneraddr" [] Decode.string


{-| The document's ID.
-}
id_ : SelectionSet SRdb.ScalarCodecs.Id SRdb.Object.Ranking
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (SRdb.ScalarCodecs.codecs |> SRdb.Scalar.unwrapCodecs |> .codecId |> .decoder)


rankingname : SelectionSet String SRdb.Object.Ranking
rankingname =
    Object.selectionForField "String" "rankingname" [] Decode.string


rankingdesc : SelectionSet (Maybe String) SRdb.Object.Ranking
rankingdesc =
    Object.selectionForField "(Maybe String)" "rankingdesc" [] (Decode.string |> Decode.nullable)


active : SelectionSet Bool SRdb.Object.Ranking
active =
    Object.selectionForField "Bool" "active" [] Decode.bool


{-| The document's timestamp.
-}
ts_ : SelectionSet SRdb.ScalarCodecs.Long SRdb.Object.Ranking
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (SRdb.ScalarCodecs.codecs |> SRdb.Scalar.unwrapCodecs |> .codecLong |> .decoder)
