module Pages.Rankings.Top exposing (Model, Msg, page)

import Element exposing (..)
import Element.Background as Background
import Element.Border as Border
import Element.Font as Font
import Element.Input as Input
import Framework
import Framework.Button
import Framework.Card as Card
import Framework.Color as Color
import Framework.Grid as Grid
import Framework.Group as Group
import Framework.Heading as Heading
import Framework.Input as Input
import Framework.Slider as Slider
import Framework.Tag as Tag
import Generated.Rankings.Params as Params
import Html
import Http
import Json.Decode
import RemoteData
import SR.Decode
import SR.Types
import Spa.Page
import Ui
import Utils.Spa exposing (Page)


page : Page Params.Top Model Msg model msg appMsg
page =
    Spa.Page.element
        { title = always "Rankings.Top"
        , init = always init
        , update = always update
        , subscriptions = always subscriptions
        , view = always view
        }



--variants are labels for different situations, with assoc data possibly attached.


type RemoteData e a
    = NotAsked
    | Loading
    | Failure e
    | Success a



--The model represents the state of the application
-- Model is what is going to change via Update (which is changed from places like View, Subs etc.)
-- it will go from 1 state to another
-- functions like view will just reflect
-- current state of model


type Model
    = AllRankingsJson (RemoteData.WebData (List SR.Types.RankingInfo))
    | NewEmpty
    | FailureOnAllRankings String



-- INIT
-- this accesses COLLECTION RECORDS - GLOBAL - public bin


init : Params.Top -> ( Model, Cmd Msg )
init _ =
    ( AllRankingsJson RemoteData.Loading
    , getRankingList
    )


getRankingList : Cmd Msg
getRankingList =
    Http.get
        { url = "https://api.jsonbin.io/b/5e2a585f593fd741856f4b04/latest"
        , expect = Http.expectJson (RemoteData.fromResult >> GotJsonbinAllRankings) SR.Decode.rankingsDecoder
        }


expectJson : (Result Http.Error a -> msg) -> Json.Decode.Decoder a -> Http.Expect msg
expectJson toMsg decoder =
    Http.expectStringResponse toMsg <|
        \response ->
            case response of
                Http.BadUrl_ url ->
                    Err (Http.BadUrl url)

                Http.Timeout_ ->
                    Err Http.Timeout

                Http.NetworkError_ ->
                    Err Http.NetworkError

                Http.BadStatus_ metadata body ->
                    Err (Http.BadStatus metadata.statusCode)

                Http.GoodStatus_ metadata body ->
                    case Json.Decode.decodeString decoder body of
                        Ok value ->
                            Ok value

                        Err err ->
                            Err (Http.BadBody (Json.Decode.errorToString err))



-- Msg is a description of the transition that already happened


type Msg
    = GotJsonbinAllRankings (RemoteData.WebData (List SR.Types.RankingInfo))
    | NewRankingCreated



-- UPDATE
-- Update needs to take two things: a message (which
-- is a description of the transition that already happened),
--  and the model (which is the model BEFORE the update is applied),
--  Update component contains code that should be executed for each message generated by the view
-- or a cmd/sub


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        GotJsonbinAllRankings rmtdata ->
            case rmtdata of
                --removes[?] the first record (created on ranking creation with different format)
                RemoteData.Success a ->
                    ( AllRankingsJson (RemoteData.Success a), Cmd.none )

                RemoteData.Failure e ->
                    ( FailureOnAllRankings "Failure", Cmd.none )

                RemoteData.NotAsked ->
                    ( FailureOnAllRankings "Not Asked", Cmd.none )

                RemoteData.Loading ->
                    ( FailureOnAllRankings "Loading", Cmd.none )

        NewRankingCreated ->
            ( NewEmpty, Cmd.none )


subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.none



-- VIEW
--The view represents the visual elements of the application and
-- will enable user to generate msgs telling Update what was done
-- It will also display whatever is currently in model


view : Model -> Element Msg
view model =
    renderView model


renderView : Model -> Element Msg
renderView model =
    html <|
        Framework.responsiveLayout [ Element.explain Debug.todo ] <|
            Element.el Framework.container <|
                Element.paragraph [ Element.explain Debug.todo ] <|
                    listOfElementmsgs
                        model



-- add any new html as Element Msg to this list


listOfElementmsgs : Model -> List (Element Msg)
listOfElementmsgs model =
    [ getHeaderGroup model

    --, viewRankingsOrError model
    ]



-- Input.button (Framework.Button.simple ++ Color.primary) <|
--         { onPress = Just NewRankingCreated
--         , label = Element.text "Create New Ranking"
--         }


getHeaderGroup : Model -> Element Msg
getHeaderGroup model =
    case model of
        AllRankingsJson rnkingList ->
            Element.column Grid.section <|
                [ Element.el Heading.h2 <| Element.text "Global Rankings"
                , Element.column (Card.fill ++ Grid.simple)
                    [ Element.wrappedRow Grid.simple
                        [ Element.el (Card.fill ++ Group.left ++ Color.disabled) <| createnewRankingbutton Color.primary NewRankingCreated "Create New"
                        , Element.el (Card.fill ++ Group.center ++ Color.disabled) <| joinbutton Color.primary NewRankingCreated "Join"
                        , Element.el (Card.fill ++ Group.right ++ Color.disabled) <| enterResultbutton Color.primary NewRankingCreated "Enter Result"
                        , Element.el (Card.fill ++ Group.top ++ Color.disabled) <| updateProfilebutton Color.primary NewRankingCreated "Update Profile"

                        --, viewRankingsOrError model
                        --, Element.el (Card.fill ++ Group.bottom) <| listAllbutton Color.primary getRankingList "List All"
                        ]
                    ]
                , Element.column (Card.fill ++ Grid.simple)
                    [ Element.wrappedRow Grid.simple
                        [ Element.el (Card.fill ++ Group.left) <| viewRankingsOrError model

                        --, Element.el (Card.fill ++ Group.bottom) <| listAllbutton Color.primary getRankingList "List All"
                        ]
                    ]

                -- , [ Element.wrappedRow Grid.simple
                --         [ Element.el (Card.fill ++ Group.left ++ Color.disabled) <| createnewRankingbutton Color.primary NewRankingCreated "Create New"
                --         , viewRankingsOrError model
                --         --, Element.el (Card.fill ++ Group.bottom) <| listAllbutton Color.primary getRankingList "List All"
                --         ]
                --   ]
                ]

        NewEmpty ->
            Element.column Grid.section <|
                [ Element.el Heading.h2 <| Element.text "Create New Ranking"
                , Element.column (Card.fill ++ Grid.simple)
                    [ Element.wrappedRow Grid.simple
                        [ Element.el (Card.fill ++ Group.left ++ Color.disabled) <| createnewRankingbutton Color.primary NewRankingCreated "Create New"
                        , Element.el (Card.fill ++ Group.center ++ Color.disabled) <| joinbutton Color.primary NewRankingCreated "Join"
                        , Element.el (Card.fill ++ Group.right ++ Color.disabled) <| enterResultbutton Color.primary NewRankingCreated "Enter Result"
                        , Element.el (Card.fill ++ Group.top ++ Color.disabled) <| updateProfilebutton Color.primary NewRankingCreated "Update Profile"

                        --, Element.el (Card.fill ++ Group.bottom) <| listAllbutton Color.primary GotJsonbinAllRankings "List All"
                        ]
                    ]
                ]

        FailureOnAllRankings s ->
            Element.column Grid.section <|
                [ Element.el Heading.h2 <| Element.text "An error occurred"
                , Element.column (Card.fill ++ Grid.simple)
                    [ Element.wrappedRow Grid.simple
                        [ Element.el (Card.fill ++ Group.left ++ Color.disabled) <| createnewRankingbutton Color.primary NewRankingCreated "Create New"
                        , Element.el (Card.fill ++ Group.center ++ Color.disabled) <| joinbutton Color.primary NewRankingCreated "Join"
                        , Element.el (Card.fill ++ Group.right ++ Color.disabled) <| enterResultbutton Color.primary NewRankingCreated "Enter Result"
                        , Element.el (Card.fill ++ Group.top ++ Color.disabled) <| updateProfilebutton Color.primary NewRankingCreated "Update Profile"

                        --, Element.el (Card.fill ++ Group.bottom) <| listAllbutton Color.primary GotJsonbinAllRankings "List All"
                        ]
                    ]
                ]



-- view : Model -> Element Msg
-- view model =
--     Element.paragraph []
--         [ viewRankingsOrError model
--         ]


viewRankingsOrError : Model -> Element Msg
viewRankingsOrError model =
    case model of
        AllRankingsJson rmtData ->
            case rmtData of
                RemoteData.NotAsked ->
                    Element.text ""

                RemoteData.Loading ->
                    Element.text "Loading..."

                RemoteData.Success rankings ->
                    viewRankings rankings

                RemoteData.Failure httpError ->
                    Element.text "(Err httpError - real value to fix here)"

        NewEmpty ->
            Element.text "ready to create a new ladder"

        FailureOnAllRankings s ->
            Element.text "failure on all"



--viewError (buildErrorMessage httpError)
--you might need this later
-- (stringFromBool ranking.active)


viewRankings : List SR.Types.RankingInfo -> Element Msg
viewRankings rankings =
    html <|
        Element.layout
            [ Element.explain Debug.todo

            --     Element.padding 25
            -- , Background.color (rgba 0 0 0 1)
            -- , Font.color (rgba 1 1 1 1)
            -- --, Font.italic
            -- , Font.size 22
            -- , Font.family
            --     [ Font.external
            --         { url = "https://fonts.googleapis.com/css?family=Roboto"
            --         , name = "Roboto"
            --         }
            --     , Font.sansSerif
            --     ]
            ]
        <|
            Element.table
                [--     Element.padding 25
                 -- , Background.color Ui.colors.white
                 -- , Border.solid
                 -- , Border.color Ui.colors.black
                 -- , Border.widthXY 1 1
                 -- , Border.rounded 3
                ]
                { data = rankings
                , columns =
                    [ rankingNameCol rankings "Ranking Name"
                    , rankingDescCol rankings "Ranking Desc"
                    ]
                }


rankingNameCol : List SR.Types.RankingInfo -> String -> Column SR.Types.RankingInfo msg
rankingNameCol _ str =
    { header = Element.text str
    , width = fill
    , view =
        \rankingInfo ->
            Element.row
                [--     Font.color Ui.colors.lightblue
                 -- , Border.widthXY 2 2
                ]
                [ Element.link
                    [--Background.color Ui.colors.blue
                     --Font.color Ui.colors.lightblue
                     --, padding 5
                     --, Border.widthXY 2 2
                    ]
                    { url = "/rankings/" ++ rankingInfo.id
                    , label = Element.text rankingInfo.name
                    }
                ]
    }


rankingDescCol : List SR.Types.RankingInfo -> String -> Column SR.Types.RankingInfo msg
rankingDescCol _ str =
    { header = Element.text str
    , width = fill
    , view =
        \rankingInfo ->
            Element.row
                [--     Border.widthXY 2 2
                 -- , Font.color Ui.colors.green
                ]
                [ Element.text rankingInfo.desc
                ]
    }



--UI


createnewRankingbutton : List (Attribute Msg) -> Msg -> String -> Element.Element Msg
createnewRankingbutton color msg label =
    Input.button (Framework.Button.simple ++ color) <|
        { onPress = Just msg
        , label = Element.text label
        }


enterResultbutton : List (Attribute Msg) -> Msg -> String -> Element.Element Msg
enterResultbutton color msg label =
    Input.button (Framework.Button.simple ++ color) <|
        { onPress = Just msg
        , label = Element.text label
        }


joinbutton : List (Attribute Msg) -> Msg -> String -> Element.Element Msg
joinbutton color msg label =
    Input.button (Framework.Button.simple ++ color) <|
        { onPress = Just msg
        , label = Element.text label
        }


updateProfilebutton : List (Attribute Msg) -> Msg -> String -> Element.Element Msg
updateProfilebutton color msg label =
    Input.button (Framework.Button.simple ++ color) <|
        { onPress = Just msg
        , label = Element.text label
        }


listAllbutton : List (Attribute Msg) -> Msg -> String -> Element.Element Msg
listAllbutton color msg label =
    Input.button (Framework.Button.simple ++ color) <|
        { onPress = Just msg
        , label = Element.text label
        }
