module Pages.Rankings.Top exposing (Model, Msg, page)

import Element exposing (..)
import Element.Background as Background
import Element.Border as Border
import Element.Font as Font
import Generated.Rankings.Params as Params
import Http
import Json.Decode
import RemoteData
import SR.Decode
import SR.Types
import Spa.Page
import Ui
import Utils.Spa exposing (Page)


page : Page Params.Top Model Msg model msg appMsg
page =
    Spa.Page.element
        { title = always "Rankings.Top"
        , init = always init
        , update = always update
        , subscriptions = always subscriptions
        , view = always view
        }



--variants are labels for different situations, with assoc data possibly attached.


type RemoteData e a
    = NotAsked
    | Loading
    | Failure e
    | Success a



--The model represents the state of the application
-- Model is what is going to change via Update (which is changed from places like View, Subs etc.)
-- it will go from 1 state to another
-- functions like view will just reflect
-- current state of model


type Model
    = JsonbinData SR.Types.SRState
    | FailureOnAllRankings String



-- INIT
-- this accesses COLLECTION RECORDS - GLOBAL - public bin


init : Params.Top -> ( Model, Cmd Msg )
init _ =
    ( JsonbinData (SR.Types.AllRankings RemoteData.Loading)
    , getRankingList
    )


getRankingList : Cmd Msg
getRankingList =
    Http.get
        { url = "https://api.jsonbin.io/b/5e2a585f593fd741856f4b04/latest"
        , expect = Http.expectJson (RemoteData.fromResult >> GotJsonbinAllRankings) SR.Decode.rankingsDecoder
        }


expectJson : (Result Http.Error a -> msg) -> Json.Decode.Decoder a -> Http.Expect msg
expectJson toMsg decoder =
    Http.expectStringResponse toMsg <|
        \response ->
            case response of
                Http.BadUrl_ url ->
                    Err (Http.BadUrl url)

                Http.Timeout_ ->
                    Err Http.Timeout

                Http.NetworkError_ ->
                    Err Http.NetworkError

                Http.BadStatus_ metadata body ->
                    Err (Http.BadStatus metadata.statusCode)

                Http.GoodStatus_ metadata body ->
                    case Json.Decode.decodeString decoder body of
                        Ok value ->
                            Ok value

                        Err err ->
                            Err (Http.BadBody (Json.Decode.errorToString err))



-- Msg is a description of the transition that needs to happen


type Msg
    = GotJsonbinAllRankings (RemoteData.WebData (List SR.Types.RankingInfo))



-- UPDATE
-- Update needs to take two things: a message (which
-- is a description of the transition that needs to happen),
--  and the model (which is the model BEFORE the update is applied),
--  Update component contains code that should be executed for each message generated by the view
-- or a cmd/sub


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        GotJsonbinAllRankings rmtdata ->
            case rmtdata of
                --removes[?] the first record (created on ranking creation with different format)
                RemoteData.Success a ->
                    ( JsonbinData (SR.Types.AllRankings (RemoteData.Success a)), Cmd.none )

                RemoteData.Failure e ->
                    ( JsonbinData (SR.Types.Failure "Failure"), Cmd.none )

                RemoteData.NotAsked ->
                    ( JsonbinData (SR.Types.Failure "Not Asked"), Cmd.none )

                RemoteData.Loading ->
                    ( JsonbinData (SR.Types.Failure "Loading"), Cmd.none )



-- SUBSCRIPTIONS


subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.none



-- VIEW
--The view represents the visual elements of the application and will generate msgs for Update
-- it will also display whatever is currently in model


view : Model -> Element Msg
view model =
    Element.paragraph []
        [ viewRankingsOrError model
        ]


viewRankingsOrError : Model -> Element Msg
viewRankingsOrError model =
    case model of
        JsonbinData srState ->
            case srState of
                SR.Types.AllRankings rmtData ->
                    case rmtData of
                        RemoteData.NotAsked ->
                            Element.text ""

                        RemoteData.Loading ->
                            Element.text "Loading..."

                        RemoteData.Success rankings ->
                            viewRankings rankings

                        RemoteData.Failure httpError ->
                            Element.text "(Err httpError - real value to fix here)"

                SR.Types.Failure s ->
                    Element.text "failure"

        FailureOnAllRankings s ->
            Element.text "failure on all"



--viewError (buildErrorMessage httpError)
--you might need this later
-- (stringFromBool ranking.active)


viewRankings : List SR.Types.RankingInfo -> Element Msg
viewRankings rankings =
    html <|
        Element.layout
            [ Element.padding 25
            , Background.color (rgba 0 0 0 1)
            , Font.color (rgba 1 1 1 1)

            --, Font.italic
            , Font.size 22
            , Font.family
                [ Font.external
                    { url = "https://fonts.googleapis.com/css?family=Roboto"
                    , name = "Roboto"
                    }
                , Font.sansSerif
                ]
            ]
        <|
            Element.table
                [ Element.padding 25
                , Background.color Ui.colors.white
                , Border.solid
                , Border.color Ui.colors.black
                , Border.widthXY 1 1
                , Border.rounded 3
                ]
                { data = rankings
                , columns =
                    [ rankingNameCol rankings "SR.Types.Ranking Name"
                    , rankingDescCol rankings "SR.Types.Ranking Desc"
                    ]
                }


rankingNameCol : List SR.Types.RankingInfo -> String -> Column SR.Types.RankingInfo msg
rankingNameCol _ str =
    { header = Element.text str
    , width = fill
    , view =
        \rankingInfo ->
            Element.row
                [ Font.color Ui.colors.lightblue
                , Border.widthXY 2 2
                ]
                [ Element.link
                    [ --Background.color Ui.colors.blue
                      Font.color Ui.colors.lightblue

                    --, padding 5
                    --, Border.widthXY 2 2
                    ]
                    { url = "/rankings/" ++ rankingInfo.id
                    , label = Element.text rankingInfo.name
                    }
                ]
    }


rankingDescCol : List SR.Types.RankingInfo -> String -> Column SR.Types.RankingInfo msg
rankingDescCol _ str =
    { header = Element.text str
    , width = fill
    , view =
        \rankingInfo ->
            Element.row
                [ Border.widthXY 2 2
                , Font.color Ui.colors.green
                ]
                [ Element.text rankingInfo.desc
                ]
    }
