-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SRdb.InputObject exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SRdb.Interface
import SRdb.Object
import SRdb.Scalar
import SRdb.ScalarCodecs
import SRdb.Union


buildPlayerInput :
    PlayerInputRequiredFields
    -> (PlayerInputOptionalFields -> PlayerInputOptionalFields)
    -> PlayerInput
buildPlayerInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { challengeraddress = Absent }
    in
    { address = required.address, rank = required.rank, challengeraddress = optionals.challengeraddress }


type alias PlayerInputRequiredFields =
    { address : String
    , rank : Int
    }


type alias PlayerInputOptionalFields =
    { challengeraddress : OptionalArgument String }


{-| Type for the PlayerInput input object.
-}
type alias PlayerInput =
    { address : String
    , rank : Int
    , challengeraddress : OptionalArgument String
    }


{-| Encode a PlayerInput into a value that can be used as an argument.
-}
encodePlayerInput : PlayerInput -> Value
encodePlayerInput input =
    Encode.maybeObject
        [ ( "address", Encode.string input.address |> Just ), ( "rank", Encode.int input.rank |> Just ), ( "challengeraddress", Encode.string |> Encode.optional input.challengeraddress ) ]


buildRankingInput :
    RankingInputRequiredFields
    -> (RankingInputOptionalFields -> RankingInputOptionalFields)
    -> RankingInput
buildRankingInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { rankingdesc = Absent }
    in
    { active = required.active, rankingname = required.rankingname, rankingdesc = optionals.rankingdesc, rankingowneraddr = required.rankingowneraddr }


type alias RankingInputRequiredFields =
    { active : Bool
    , rankingname : String
    , rankingowneraddr : String
    }


type alias RankingInputOptionalFields =
    { rankingdesc : OptionalArgument String }


{-| Type for the RankingInput input object.
-}
type alias RankingInput =
    { active : Bool
    , rankingname : String
    , rankingdesc : OptionalArgument String
    , rankingowneraddr : String
    }


{-| Encode a RankingInput into a value that can be used as an argument.
-}
encodeRankingInput : RankingInput -> Value
encodeRankingInput input =
    Encode.maybeObject
        [ ( "active", Encode.bool input.active |> Just ), ( "rankingname", Encode.string input.rankingname |> Just ), ( "rankingdesc", Encode.string |> Encode.optional input.rankingdesc ), ( "rankingowneraddr", Encode.string input.rankingowneraddr |> Just ) ]


buildUserInput :
    UserInputRequiredFields
    -> (UserInputOptionalFields -> UserInputOptionalFields)
    -> UserInput
buildUserInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { description = Absent, email = Absent, mobile = Absent }
    in
    { active = required.active, username = required.username, password = required.password, ethaddress = required.ethaddress, description = optionals.description, email = optionals.email, mobile = optionals.mobile, member_since = required.member_since }


type alias UserInputRequiredFields =
    { active : Bool
    , username : String
    , password : String
    , ethaddress : String
    , member_since : Int
    }


type alias UserInputOptionalFields =
    { description : OptionalArgument String
    , email : OptionalArgument String
    , mobile : OptionalArgument String
    }


{-| Type for the UserInput input object.
-}
type alias UserInput =
    { active : Bool
    , username : String
    , password : String
    , ethaddress : String
    , description : OptionalArgument String
    , email : OptionalArgument String
    , mobile : OptionalArgument String
    , member_since : Int
    }


{-| Encode a UserInput into a value that can be used as an argument.
-}
encodeUserInput : UserInput -> Value
encodeUserInput input =
    Encode.maybeObject
        [ ( "active", Encode.bool input.active |> Just ), ( "username", Encode.string input.username |> Just ), ( "password", Encode.string input.password |> Just ), ( "ethaddress", Encode.string input.ethaddress |> Just ), ( "description", Encode.string |> Encode.optional input.description ), ( "email", Encode.string |> Encode.optional input.email ), ( "mobile", Encode.string |> Encode.optional input.mobile ), ( "member_since", Encode.int input.member_since |> Just ) ]


buildUserJoinedRankingInput :
    UserJoinedRankingInputRequiredFields
    -> UserJoinedRankingInput
buildUserJoinedRankingInput required =
    { active = required.active, rankingid = required.rankingid, rankingname = required.rankingname, useraddr = required.useraddr, rankingowneraddr = required.rankingowneraddr }


type alias UserJoinedRankingInputRequiredFields =
    { active : Bool
    , rankingid : String
    , rankingname : String
    , useraddr : String
    , rankingowneraddr : String
    }


{-| Type for the UserJoinedRankingInput input object.
-}
type alias UserJoinedRankingInput =
    { active : Bool
    , rankingid : String
    , rankingname : String
    , useraddr : String
    , rankingowneraddr : String
    }


{-| Encode a UserJoinedRankingInput into a value that can be used as an argument.
-}
encodeUserJoinedRankingInput : UserJoinedRankingInput -> Value
encodeUserJoinedRankingInput input =
    Encode.maybeObject
        [ ( "active", Encode.bool input.active |> Just ), ( "rankingid", Encode.string input.rankingid |> Just ), ( "rankingname", Encode.string input.rankingname |> Just ), ( "useraddr", Encode.string input.useraddr |> Just ), ( "rankingowneraddr", Encode.string input.rankingowneraddr |> Just ) ]
