-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SRdb.Object exposing (..)


type Player
    = Player


type Ranking
    = Ranking


type User
    = User


type UserJoinedRanking
    = UserJoinedRanking
